### ISSUE TITLE
Ionic2 on iOS - this.chart.destroy is not a function

### ISSUE THREAD

**Issue by smukov** [ihadeed/ng2-chartjs2#9]
I'm getting the below error when I navigate away from a page that contains a chart:

`this.chart.destory is not a function. (In 'this.chart.destory()', 'this.chart.destory' is undefined)`

I haven't seen this issue on my Android device.

**Comment by ihadeed** [comment]
Thanks for reporting the issue. I will look into it when I get a chance.
Probably within the next 24 hours.

**Comment by ihadeed** [comment]
@smukov @wangtiantian2016 this should be fixed now, please update to v1.1.1

**Comment by wangtiantian2016** [comment]
@ihadeed 
Thank you very much. 
But the error still happened. I think the reason is that the code is "this.chart.destroy()" instead of "this.chart.destory()" in  line 96 of chart.ts file.

**Comment by cjdreiss** [comment]
I'm getting this error as well.  Using v1.1.1  Also using the minified version of chart.js, not sure if that matters.  Will try with the un-minified version.  Using Ionic2 RC0. I get this error using ionic serve and when it builds in iOS as well, when I leave a page that has a chart this error happens, and after 2 or 3 more page changes the whole app breaks.

`TypeError: this.chart.destory is not a function. (In 'this.chart.destory()', 'this.chart.destory' is undefined)`

**Comment by cjdreiss** [comment]
In the package I have from NPM, `components/chart.js` still has the wrong spelling.  
lines 68-71  

```
ChartComponent.prototype.destroy = function () {
        if (typeof this.chart !== 'undefined' && typeof this.chart.destroy === 'function')
            this.chart.destory();
    };
```

**Comment by cjdreiss** [comment]
If you search the repo on github you can find it as well
https://github.com/zyramedia/ng2-chartjs2/search?utf8=%E2%9C%93&q=destory

**Comment by ihadeed** [comment]
Should be fixed now, please update to `ng2-chartjs2@1.1.2`

**Comment by cjdreiss** [comment]
It works now in 1.1.2, thanks!
